---
title: "Visualization for Data Mining"
output:
  ioslides_presentation
---

## Conceptual framework

- Visual methods for high-dimensional data are well-developed and understood. Toolbox includes:
  + scatterplot matrics
  + parallel coordinate plots
  + interactive tools like brushing and linking
  + dynamic methods like tours
- These methods can also be used to visualise our models, often leading to some surprise that the fitted models may be different from expected.

## Questions to answer

- What does the model look like? How does the model change when its parameters change? How do the parameters change when the data is changed?
- How well does the model fit the data? How does the shape of the model compare to the shape of the data? Is the model fitting uniformly good, or good in some regions but poor in other regions? Where might the fit be improved?

## Key strategies

- Display the model in data space (m-in-ds), as well as the data in the model space.
- Look at all members of a collection of a model, not just a single one.
- Explore the process of fitting, not just the end result.
## Outline

* The Toolbox: Grammar of graphics, multivariate data plots, dimension reduction, interactive graphics
* Supervised Classification: Checking assumptions, examining misclassifications, variable importance, visualising boundaries, exploring ensembles
* Trees: Exploring splits, oblique trees
* Forests: Variable importance, confusion table, vote matrix, 
proximity matrix, oblique forest shiny app
* Support vector machines: support vectors, boundary
* Neural networks: Components
* High-dimension, small sample size

## Toolbox

* Grammar of graphics
* Multivariate data plots 
* Dimension reduction 
* Interactive graphics

## Grammar of graphics

* 

## Multivariate plots

* Parallel coordinate plot
* Tours

## Dimension reduction

* Principal componenent analysis
* Projection pursuit

## Supervised Classification

* Checking assumptions
* Examining misclassifications
* Variable importance
* Visualising boundaries
* Exploring ensembles

## Checking assumptions

* LDA: equal variance-covariances
* 

## Examining misclassifications

Linking confusion table with data plots

## Variable importance

Ordering par coords by importance

## Visualising boundaries

Predicting grid and viewing with tour

## Exploring ensembles

* Diagnostics
* Pruning

## Trees

## Sources

- Wickham, Cook, Hofmann (2015) Visualizing statistical models: Removing the blindfold, Statistical Analysis and Data Mining, (http://dx.doi.org/10.1002/sam.11271)
- Cook and Swayne (2007) Interactive and Dynamic Graphics for Data Analysis: With Examples Using R and GGobi (http://www.ggobi.org/book/)

